REM This file shows the values of the Windows Environment Variables presented in the following article:
REM https://www.itprotoday.com/cloud-computing/what-environment-variables-are-available-windows

ECHO ALLUSERSPROFILE: %ALLUSERSPROFILE%
ECHO APPDATA: %APPDATA%
ECHO CD: %CD%
ECHO CMDCMDLINE: %CMDCMDLINE%
ECHO CMDEXTVERSION: %CMDEXTVERSION%
ECHO COMPUTERNAME: %COMPUTERNAME%
ECHO COMSPEC: %COMSPEC%
ECHO DATE: %DATE%
ECHO ERRORLEVEL: %ERRORLEVEL%
ECHO HOMEDRIVE: %HOMEDRIVE%
ECHO HOMEPATH: %HOMEPATH%
ECHO HOMESHARE: %HOMESHARE%
ECHO LOGONSEVER: %LOGONSEVER%
ECHO NUMBER_OF_PROCESSORS: %NUMBER_OF_PROCESSORS%
ECHO PATH: %PATH%
ECHO PATHEXT: %PATHEXT%
ECHO PROCESSOR_ARCHITECTURE: %PROCESSOR_ARCHITECTURE%
ECHO PROCESSOR_IDENTFIER: %PROCESSOR_IDENTFIER%
ECHO PROCESSOR_LEVEL: %PROCESSOR_LEVEL%
ECHO PROCESSOR_REVISION: %PROCESSOR_REVISION%
ECHO PROMPT:%PROMPT%
ECHO RANDOM: %RANDOM%
ECHO SYSTEMDRIVE: %SYSTEMDRIVE%
ECHO SYSTEMROOT: %SYSTEMROOT%
ECHO TEMP: %TEMP%
ECHO TMP: %TMP%
ECHO TIME: %TIME%
ECHO USERDOMAIN: %USERDOMAIN%
ECHO USERNAME: %USERNAME%
ECHO USERPROFILE: %USERPROFILE%
ECHO WINDIR: %WINDIR%


PAUSE



